# 
# Push request triggered by a push to master branch.
#
# This workflow will:
#  - generate Sphinx documentation
#  - upload Sphinx documentation to GitHub Pages
#  - submit project state to Sonarccloud.
#
# It does not perform linting or formatting checks, or run tests, presuming that they have already been checked on the dev
# branches.
#

name: python_ci_push_master

on:
  workflow_call:
    inputs:
      library-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true        

jobs:
        
  sphinx:
    uses: ./.github/workflows/_sphinx.yml
    with:
      artifact-name: ${{ inputs.library-name }}-docs
    secrets: inherit

  sonarcloud:
    uses: ./.github/workflows/_sonarcloud.yml
    secrets: inherit
