# 
# Push request triggered by a push to dev branch.
#
# This workflow will:
#  - perform linting/formatting checks (on Python 3.11 only)
#  - run unit tests (on Python 3.11 only)
#  - submit project state to Sonarccloud.submit to Sonarccloud.
#
#

name: Python CI for Development branch

on:
  workflow_call:
    inputs:
      library-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true        


jobs:
  lint_test:
    uses: ./.github/workflows/_lint_test.yml
    with:
      target_version: '3.11'

